### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by yonilerner** [Xentradi/undervoltWatcher#1]
Hey, love that you did this, I actually forked this a while back for use with my XPS 9560 and its been working wonderfully. I had a question about https://github.com/Xentradi/undervoltWatcher/blob/master/undervoltWatch#L5
```
killall -q undervoltWatch
while pgrep -u $UID -x undervoltWatch >/dev/null; do sleep 1; done
```
What did this do and why was it necessary? I was actually only able to get it to work by removing those lines.

On a separate note, in my fork I did a little refactor to make the undervolt configurable using service environment variables, if youre interested

**Comment by Xentradi** [comment]
Glad it worked for you. If I remember right it was to make sure only one instance of the watcher was running. 

I had to switch my 9730 back to windows for work applications so I'mma not using this anymore
